const playingCards = [
    {
        id:52,
        name: 'Ace of Clubs',
        suit: 'Clubs',
        value: 14,
        hasAltValue: true,
        img:require('../../images/AC.png'),
    },
    {
        id:51,
        name: 'Ace of Spades',
        suit: 'Spades',
        value: 14,
        hasAltValue: true,
        img:require('../../images/AS.png'),
    },
    {   
        id:50,
        name: 'Ace of Diamonds',
        suit: 'Diamonds',
        value: 14,
        hasAltValue: true,
        img:require('../../images/AD.png'),
    },
    {
        id:49,
        name: 'Ace of Hearts',
        suit: 'Hearts',
        value: 14,
        hasAltValue: true,
        img:require('../../images/AH.png'),
    },
    {
        id:48,
        name: 'King of Clubs',
        suit: 'Clubs',
        value: 13,
        hasAltValue: false,
        img:require('../../images/KC.png'),
    },
    {
        id:47,
        name: 'King of Spades',
        suit: 'Spades',
        value: 13,
        hasAltValue: false,
        img:require('../../images/KS.png'),
    },
    {   
        id:46,
        name: 'King of Diamonds',
        suit: 'Diamonds',
        value: 13,
        hasAltValue: false,
        img:require('../../images/KD.png'),
    },
    {
        id:45,
        name: 'King of Hearts',
        suit: 'Hearts',
        value: 13,
        hasAltValue: false,
        img:require('../../images/KH.png'),
    },
    {
        id:44,
        name: 'Queen of Clubs',
        suit: 'Clubs',
        value: 12,
        hasAltValue: false,
        img:require('../../images/QC.png'),
    },
    {
        id:43,
        name: 'Queen of Spades',
        suit: 'Spades',
        value: 12,
        hasAltValue: false,
        img:require('../../images/QS.png'),
    },
    {   
        id:42,
        name: 'Queen of Diamonds',
        suit: 'Diamonds',
        value: 12,
        hasAltValue: false,
        img:require('../../images/QD.png'),
    },
    {
        id:41,
        name: 'Queen of Hearts',
        suit: 'Hearts',
        value: 12,
        hasAltValue: false,
        img:require('../../images/QH.png'),
    },
    {
        id:40,
        name: 'Jack of Clubs',
        suit: 'Clubs',
        value: 11,
        hasAltValue: false,
        img:require('../../images/JC.png'),
    },
    {
        id:39,
        name: 'Jack of Spades',
        suit: 'Spades',
        value: 11,
        hasAltValue: false,
        img:require('../../images/JS.png'),
    },
    {   
        id:38,
        name: 'Jack of Diamonds',
        suit: 'Diamonds',
        value: 11,
        hasAltValue: false,
        img:require('../../images/JD.png'),
    },
    {
        id:37,
        name: 'Jack of Hearts',
        suit: 'Hearts',
        value: 11,
        hasAltValue: false,
        img:require('../../images/JH.png'),
    },
    {
        id:36,
        name: 'Ten of Clubs',
        suit: 'Clubs',
        value: 10,
        hasAltValue: false,
        img:require('../../images/10C.png'),
    },
    {
        id:35,
        name: 'Ten of Spades',
        suit: 'Spades',
        value: 10,
        hasAltValue: false,
        img:require('../../images/10S.png'),
    },
    {   
        id:34,
        name: 'Ten of Diamonds',
        suit: 'Diamonds',
        value: 10,
        hasAltValue: false,
        img:require('../../images/10D.png'),
    },
    {
        id:33,
        name: 'Ten of Hearts',
        suit: 'Hearts',
        value: 10,
        hasAltValue: false,
        img:require('../../images/10H.png'),
    },
    {
        id:32,
        name: 'Nine of Clubs',
        suit: 'Clubs',
        value: 9,
        hasAltValue: false,
        img:require('../../images/9C.png'),
    },
    {
        id:31,
        name: 'Nine of Spades',
        suit: 'Spades',
        value: 9,
        hasAltValue: false,
        img:require('../../images/9S.png'),
    },
    {   
        id:30,
        name: 'Nine of Diamonds',
        suit: 'Diamonds',
        value: 9,
        hasAltValue: false,
        img:require('../../images/9D.png'),
    },
    {
        id:29,
        name: 'Nine of Hearts',
        suit: 'Hearts',
        value: 9,
        hasAltValue: false,
        img:require('../../images/9H.png'),
    },
    {
        id:28,
        name: 'Eight of Clubs',
        suit: 'Clubs',
        value: 8,
        hasAltValue: false,
        img:require('../../images/8C.png'),
    },
    {
        id:27,
        name: 'Eight of Spades',
        suit: 'Spades',
        value: 8,
        hasAltValue: false,
        img:require('../../images/8S.png'),
    },
    {   
        id:26,
        name: 'Eight of Diamonds',
        suit: 'Diamonds',
        value: 8,
        hasAltValue: false,
        img:require('../../images/8D.png'),
    },
    {
        id:25,
        name: 'Eight of Hearts',
        suit: 'Hearts',
        value: 8,
        hasAltValue: false,
        img:require('../../images/8H.png'),
    },
    {
        id:24,
        name: 'Seven of Clubs',
        suit: 'Clubs',
        value: 7,
        hasAltValue: false,
        img:require('../../images/7C.png'),
    },
    {
        id:23,
        name: 'Seven of Spades',
        suit: 'Spades',
        value: 7,
        hasAltValue: false,
        img:require('../../images/7S.png'),
    },
    {   
        id:22,
        name: 'Seven of Diamonds',
        suit: 'Diamonds',
        value: 7,
        hasAltValue: false,
        img:require('../../images/7D.png'),
    },
    {
        id:21,
        name: 'Seven of Hearts',
        suit: 'Hearts',
        value: 7,
        hasAltValue: false,
        img:require('../../images/7H.png'),
    },
    {
        id:20,
        name: 'Six of Clubs',
        suit: 'Clubs',
        value: 6,
        hasAltValue: false,
        img:require('../../images/6C.png'),
    },
    {
        id:19,
        name: 'Six of Spades',
        suit: 'Spades',
        value: 6,
        hasAltValue: false,
        img:require('../../images/6S.png'),
    },
    {   
        id:18,
        name: 'Six of Diamonds',
        suit: 'Diamonds',
        value: 6,
        hasAltValue: false,
        img:require('../../images/6D.png'),
    },
    {
        id:17,
        name: 'Six of Hearts',
        suit: 'Hearts',
        value: 6,
        hasAltValue: false,
        img:require('../../images/6H.png'),
    },
    {
        id:16,
        name: 'Five of Clubs',
        suit: 'Clubs',
        value: 5,
        hasAltValue: false,
        img:require('../../images/5C.png'),
    },
    {
        id:15,
        name: 'Five of Spades',
        suit: 'Spades',
        value: 5,
        hasAltValue: false,
        img:require('../../images/5S.png'),
    },
    {   
        id:14,
        name: 'Five of Diamonds',
        suit: 'Diamonds',
        value: 5,
        hasAltValue: false,
        img:require('../../images/5D.png'),
    },
    {
        id:13,
        name: 'Five of Hearts',
        suit: 'Hearts',
        value: 5,
        hasAltValue: false,
        img:require('../../images/5H.png'),
    },
    {
        id:12,
        name: 'Four of Clubs',
        suit: 'Clubs',
        value: 4,
        hasAltValue: false,
        img:require('../../images/4C.png'),
    },
    {
        id:11,
        name: 'Four of Spades',
        suit: 'Spades',
        value: 4,
        hasAltValue: false,
        img:require('../../images/4S.png'),
    },
    {   
        id:10,
        name: 'Four of Diamonds',
        suit: 'Diamonds',
        value: 4,
        hasAltValue: false,
        img:require('../../images/4D.png'),
    },
    {
        id:9,
        name: 'Four of Hearts',
        suit: 'Hearts',
        value: 4,
        hasAltValue: false,
        img:require('../../images/4H.png'),
    },
    {
        id:8,
        name: 'Three of Clubs',
        suit: 'Clubs',
        value: 3,
        hasAltValue: false,
        img:require('../../images/3C.png'),
    },
    {
        id:7,
        name: 'Three of Spades',
        suit: 'Spades',
        value: 3,
        hasAltValue: false,
        img:require('../../images/3S.png'),
    },
    {   
        id:6,
        name: 'Three of Diamonds',
        suit: 'Diamonds',
        value: 3,
        hasAltValue: false,
        img:require('../../images/3D.png'),
    },
    {
        id:5,
        name: 'Three of Hearts',
        suit: 'Hearts',
        value: 3,
        hasAltValue: false,
        img:require('../../images/3H.png'),
    },
    {
        id:4,
        name: 'Two of Clubs',
        suit: 'Clubs',
        value: 2,
        hasAltValue: false,
        img:require('../../images/2C.png'),
    },
    {
        id:3,
        name: 'Two of Spades',
        suit: 'Spades',
        value: 2,
        hasAltValue: false,
        img:require('../../images/2S.png'),
    },
    {
        id:2,
        name: 'Two of Diamonds',
        suit: 'Diamonds',
        value: 2,
        hasAltValue: false,
        img:require('../../images/2D.png'),
    },
    {
        id:1,
        name: 'Two of Hearts',
        suit: 'Hearts',
        value: 2,
        hasAltValue: false,
        img:require('../../images/2H.png'),
    },
]

export default playingCards;